### ISSUE TITLE
Results in script not matching results in browser.

### ISSUE THREAD

**Issue by nick-ft** [m8sec/pymeta#11]
While running the script (have tested local, and on a few ec2 instances), I am seeing very few, and often no results on several domains no matter my environment, screenshot below:
![image](https://user-images.githubusercontent.com/60763433/162278223-6cd62b64-b287-4115-b911-5a9dcd56c23b.png)

When manually dorking in browser, I am served with a result count different from in pymeta, screenshot below:
![image](https://user-images.githubusercontent.com/60763433/162265234-a038793d-c204-4e4d-9ff6-c68869f8fa95.png)

I sincerely appreciate your work on this script, and would be grateful for any troubleshooting advice or observations.

*updated screenshot.

**Comment by m8sec** [comment]
Hi @nick-ft,

Appreciate the issue and I apologize for taking so long to get back to you. 

I just updated the code and changed how the search class works. I hope this provides more detailed results - during testing this appeared to provide a vast improvement on my end....  That said, PyMeta is an automated solution and its a constant cat-and-mouse game with search engines blocking tools just like this. I wouldn't expect 100% accuracy but we are going to try 😄
